---
- hosts: all
  tasks:
    - name: setup packages for RHEL
      include: Template-Packages-RHEL.yml
    - name: setup packages for Debian/Ubuntu
      include: Template-Packages-Debian.yml

    - name: disable sysklogd (if present)
      service: name=syslog enabled=no
      ignore_errors: true
    - name: enable rsyslog (if not)
      service: name=rsyslog enabled=yes

    - name: remove cloud user
      user: name=cloud state=absent

    - name: add CloudStack login splash (Ubuntu)
      template: src=templates/motd.j2 dest=/etc/motd.tail
      when: ansible_distribution == "Ubuntu"
    - name: add CloudStack login spash (Others)
      template: src=templates/motd.j2 dest=/etc/motd
      when: ansible_distribution != "Ubuntu"
    - name: create ssh directory
      file: state=directory mode=0700 path=/root/.ssh

    - name: create directory to store password and ssh key scripts
      file: state=directory mode=0755 path=/usr/share/cloudstack
    - name: add cloud-set-guest-sshkey script (RHEL)
      when: ansible_os_family == "RedHat"
      template: src=templates/cloud-set-guest-sshkey-centos.j2 dest=/usr/share/cloudstack/cloudstack-set-guest-sshkey mode=0755
    - name: add cloud-set-guest-password script (RHEL)
      when: ansible_os_family == "RedHat"
      template: src=templates/cloud-set-guest-password-centos.j2 dest=/usr/share/cloudstack/cloudstack-set-guest-password mode=0755
    - name: add cloud-set-guest-sshkey script (Debian)
      when: ansible_distribution == "Debian"
      template: src=templates/cloud-set-guest-sshkey-debian.j2 dest=/usr/share/cloudstack/cloudstack-set-guest-sshkey mode=0755
    - name: add cloud-set-guest-password script (Debian)
      when: ansible_distribution == "Debian"
      template: src=templates/cloud-set-guest-password-debian.j2 dest=/usr/share/cloudstack/cloudstack-set-guest-password mode=0755
    - name: add cloud-set-guest-sshkey script (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      template: src=templates/cloud-set-guest-sshkey-ubuntu.j2 dest=/usr/share/cloudstack/cloudstack-set-guest-sshkey mode=0755
    - name: add cloud-set-guest-password script (Debian)
      when: ansible_distribution == "Ubuntu"
      template: src=templates/cloud-set-guest-password-ubuntu.j2 dest=/usr/share/cloudstack/cloudstack-set-guest-password mode=0755

    - name: register primary network adapter name
      shell: "ip link | grep UP | grep -v LOOPBACK | awk -F':' '{print $2}' | tr -d ' '"
      register: adapter_name

    - name: setup networking (RHEL)
      when: ansible_os_family == "RedHat"
      template: src=templates/ifcfg-rhel.j2 dest=/etc/sysconfig/network-scripts/ifcfg-{{adapter_name.stdout}} mode=0644
    - name: remove udev network naming (RHEL) (1/2)
      when: ansible_os_family == "RedHat"
      file: path=/etc/udev/rules.d/70-persistent-net.rules state=absent

    - name: setup networking (Debian)
      when: ansible_os_family == "Debian"
      template: src=templates/ifcfg-debian.j2 dest=/etc/network/interfaces mode=0644

    - name: setup firstboot-cloudstack (RHEL)
      when: ansible_os_family == "RedHat"
      template: src=templates/firstboot-rhel.sh.j2 dest=/etc/init.d/firstboot-cloudstack mode=0755
    - name: setup firstboot-cloudstack (Debian)
      when: ansible_os_family == "Debian"
      template: src=templates/firstboot-debian.sh.j2 dest=/etc/init.d/firstboot-cloudstack mode=0755
    - name: setup firstboot-cloudstack (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      template: src=templates/firstboot.upstart.j2 dest=/etc/init/firstboot-cloudstack mode=0644
    - name: setup cloudstack-set-guest-password (init)
      file: state=link src=/usr/share/cloudstack/cloudstack-set-guest-password dest=/etc/init.d/cloudstack-set-guest-password mode=0755 force=yes
    - name: setup cloudstack-set-guest-sshkey (init)
      file: state=link src=/usr/share/cloudstack/cloudstack-set-guest-sshkey dest=/etc/init.d/cloudstack-set-guest-sshkey mode=0755 force=yes
    - name: setup cloudstack-set-guest-password (upstart)
      when: ansible_distribution == "Ubuntu"
      template: src=templates/set-guest-password.upstart.j2 dest=/etc/init/cloudstack-set-guest-password mode=0644
    - name: setup cloudstack-set-guest-sshkey (upstart)
      when: ansible_distribution == "Ubuntu"
      template: src=templates/set-guest-sshkey.upstart.j2 dest=/etc/init/cloudstack-set-guest-sshkey mode=0644
    - name: setup cloudstack-set-guest-sshkey (systemd)
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7
      template: src=templates/set-guest-sshkey.systemd.j2 dest=/usr/lib/systemd/system/cloudstack-set-guest-sshkey.service mode=0644 
    - name: setup cloudstack-set-guest-password (systemd)
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7
      template: src=templates/set-guest-password.systemd.j2 dest=/usr/lib/systemd/system/cloudstack-set-guest-password.service mode=0644

    - name: enable cloudstack-password service
      service: name=cloudstack-set-guest-password enabled=yes
    - name: enable cloudstack-sshkey service
      service: name=cloudstack-set-guest-sshkey enabled=yes
    - name: enable firstboot-cloudstack service
      service: name=firstboot-cloudstack enabled=yes

    - name: remove upstart overrides (if present)
      file: path=/etc/init/firstboot-cloudstack.override state=absent
    - name: remove shell history
      shell: rm -f /root/.*history*
    - name: remove dhcp history
      shell: rm -f /var/lib/dhc*/dhclient*leas*
