---
- hosts: all
  tasks:
    - name: create directory to store cloudstack client scripts
      file: state=directory mode=0755 path=/usr/share/cloudstack

    - name: register init system variables
      include: Template-Test-Init-System.yml

    - name: setup common functions for init scripts
      include: Template-Cloud-Functions.yml

    - name: setup cloudstack-set-guest-password
      include: Template-Cloud-Password.yml
    - name: setup cloudstack-set-guest-sshkey
      include: Template-Cloud-SSH-Key.yml
    - name: setup cloudstack-run-userdata
      include: Template-Cloud-Userdata.yml
    - name: setup cloudstack-firstboot
      include: Template-Cloud-Firstboot.yml

    - name: register upstart services
      when: upstart.stat.exists == true and systemd.stat.exists == false
      shell: initctl reload-configuration
    - name: register systemd services
      when: upstart.stat.exists == false and systemd.stat.exists == true
      shell: systemctl daemon-reload

    - name: enable cloudstack-password service
      service: name=cloudstack-set-guest-password enabled=yes
    - name: enable cloudstack-sshkey service
      service: name=cloudstack-set-guest-sshkey enabled=yes
    - name: enable cloudstack-userdata service
      service: name=cloudstack-run-userdata enabled=yes
#    - name: enable firstboot-cloudstack service
#      service: name=cloudstack-firstboot enabled=yes
